# -*- coding: utf-8 -*-
"""Final Project spam email and phising url detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15O5CvanShzO3BPOmYBmA1m-DuVlzjXb1

### ============================================================
# SPAM EMAIL & PHISHING URL DETECTOR
# Final Version - All Steps Included
# ============================================================
# HOW TO USE:
# Copy each CELL into your Google Colab notebook one by one
# Run them in order from top to bottom
# ============================================================

# ============================================================
# CELL 1 — Install All Required Libraries
# ============================================================

!pip install transformers torch gradio scikit-learn pandas numpy matplotlib seaborn nltk -q

# ============================================================
# CELL 3 — Import All Libraries
# ============================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob
import pickle
import re
import warnings
warnings.filterwarnings('ignore')

import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, classification_report,
                              roc_curve, auc)
from scipy.sparse import hstack, csr_matrix
from urllib.parse import urlparse

print("✅ All libraries imported successfully!")

"""To access files from Google Drive, we first need to mount it."""

from google.colab import drive
drive.mount('/content/drive')

"""### Listing contents of `email-phishing-detector` folder"""

import os

folder_path = '/content/drive/MyDrive/email-phishing-detector/'

if os.path.exists(folder_path):
    print(f"Contents of '{folder_path}':")
    for item in os.listdir(folder_path):
        item_path = os.path.join(folder_path, item)
        if os.path.isfile(item_path):
            print(f"  - File: {item}")
        elif os.path.isdir(item_path):
            print(f"  - Directory: {item}/")
else:
    print(f"Error: The folder '{folder_path}' does not exist or is not accessible.")

"""
# ============================================================
# CELL 4 — Load Spam Email Dataset
# ============================================================
"""

import pandas as pd
import glob
import os

spam_dataset_folder = '/content/drive/MyDrive/email-phishing-detector/spam_email dataset/'

# Direct list karo glob ki bajaye
all_csv_files = [
    os.path.join(spam_dataset_folder, f)
    for f in os.listdir(spam_dataset_folder)
    if f.endswith('.csv')
]

print(f"Found {len(all_csv_files)} CSV files:")
for f in all_csv_files:
    print(f"   {f}")

dataframes = []
for f in all_csv_files:
    try:
        df = pd.read_csv(f, encoding='utf-8', on_bad_lines='skip')
        dataframes.append(df)
        print(f"✅ Loaded: {os.path.basename(f)} — Shape: {df.shape}")
    except Exception as e:
        print(f"❌ Error: {os.path.basename(f)} — {e}")

if dataframes:
    spam_df = pd.concat(dataframes, ignore_index=True)
    print(f"\n✅ Combined dataset shape: {spam_df.shape}")
    print(f"Columns: {spam_df.columns.tolist()}")
else:
    print("❌ No dataframes loaded.")

"""# ============================================================
# CELL 5 — Clean & Preprocess Spam Dataset
# ============================================================

"""

# Fix text columns
text_columns = spam_df.select_dtypes(include='object').columns
for col in text_columns:
    spam_df[col] = spam_df[col].fillna('')

# Create combined text column
if 'subject' in spam_df.columns and 'body' in spam_df.columns:
    spam_df['text_combined'] = spam_df['subject'].astype(str) + ' ' + spam_df['body'].astype(str)
elif 'body' in spam_df.columns:
    spam_df['text_combined'] = spam_df['body'].astype(str)
else:
    text_cols = spam_df.select_dtypes(include='object').columns.tolist()
    spam_df['text_combined'] = spam_df[text_cols[0]].astype(str)

# Fix URLs column
if 'urls' in spam_df.columns:
    spam_df['urls'] = pd.to_numeric(spam_df['urls'], errors='coerce').fillna(0)

# Remove duplicates
before = spam_df.shape[0]
spam_df.drop_duplicates(inplace=True)
print(f"✅ Removed {before - spam_df.shape[0]} duplicate rows")
print(f"✅ Dataset shape after cleaning: {spam_df.shape}")

# Check label column
print(f"\nLabel distribution:\n{spam_df['label'].value_counts()}")

"""
# ============================================================
# CELL 6 — Text Preprocessing (Normalize, Tokenize, Lemmatize)
# ============================================================
"""

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    """Full text preprocessing pipeline"""
    # Lowercase
    text = str(text).lower()
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove special characters
    text = re.sub(r'[^\w\s]', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Tokenize
    tokens = word_tokenize(text)
    # Remove stop words and lemmatize
    tokens = [lemmatizer.lemmatize(t) for t in tokens if t not in stop_words and len(t) > 2]
    return ' '.join(tokens)

print("Preprocessing text (this may take a few minutes)...")
spam_df['text_processed'] = spam_df['text_combined'].apply(preprocess_text)

# Remove zero-length messages
spam_df = spam_df[spam_df['text_processed'].str.len() > 0].reset_index(drop=True)
print(f"✅ Text preprocessing complete. Dataset shape: {spam_df.shape}")
print(f"\nSample processed text:\n{spam_df['text_processed'].iloc[0][:200]}")

"""
# ============================================================
# CELL 7 — TF-IDF Vectorization + Feature Engineering
# ============================================================
"""

# TF-IDF with bigrams for better context
tfidf_vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),   # unigrams + bigrams — better than (1,1)
    min_df=2,
    max_df=0.95,
    sublinear_tf=True     # log normalization
)

X_tfidf = tfidf_vectorizer.fit_transform(spam_df['text_processed'])

# Add numerical features
if 'urls' in spam_df.columns:
    spam_df['urls'] = pd.to_numeric(spam_df['urls'], errors='coerce').fillna(0)
    spam_df['urls_transformed'] = np.log1p(spam_df['urls'])
    spam_df['text_length'] = spam_df['text_processed'].apply(len)
    spam_df['text_length_transformed'] = np.log1p(spam_df['text_length'])
    numerical_features = spam_df[['urls_transformed', 'text_length_transformed']].values
    X_combined = hstack([X_tfidf, csr_matrix(numerical_features)])
else:
    spam_df['text_length'] = spam_df['text_processed'].apply(len)
    spam_df['text_length_transformed'] = np.log1p(spam_df['text_length'])
    numerical_features = spam_df[['text_length_transformed']].values
    X_combined = hstack([X_tfidf, csr_matrix(numerical_features)])

y_spam = spam_df['label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_combined, y_spam, test_size=0.2, random_state=42, stratify=y_spam
)

print(f"✅ TF-IDF + Feature Matrix ready")
print(f"   X_train: {X_train.shape} | X_test: {X_test.shape}")
print(f"   Label distribution in train:\n{pd.Series(y_train).value_counts()}")

"""
# ============================================================
# CELL 8 — Train ALL Spam Detection Models
# ============================================================
"""

# --- Model 1: Multinomial Naive Bayes ---
print("Training Multinomial Naive Bayes...")
mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred_mnb = mnb.predict(X_test)
acc_mnb = accuracy_score(y_test, y_pred_mnb)
f1_mnb = f1_score(y_test, y_pred_mnb, average='weighted')
print(f"  ✅ MNB — Accuracy: {acc_mnb:.4f} | F1: {f1_mnb:.4f}")

# --- Model 2: Logistic Regression ---
print("Training Logistic Regression...")
lr = LogisticRegression(solver='liblinear', max_iter=1000, random_state=42)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
acc_lr = accuracy_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr, average='weighted')
print(f"  ✅ LR  — Accuracy: {acc_lr:.4f} | F1: {f1_lr:.4f}")

# --- Model 3: Linear SVM ---
print("Training Linear SVM...")
svm = LinearSVC(max_iter=2000, random_state=42, dual=False)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
acc_svm = accuracy_score(y_test, y_pred_svm)
f1_svm = f1_score(y_test, y_pred_svm, average='weighted')
print(f"  ✅ SVM — Accuracy: {acc_svm:.4f} | F1: {f1_svm:.4f}")

# --- Model 4: Hyperparameter Tuned SVM (GridSearchCV) ---
print("Training Tuned SVM with GridSearchCV (may take 5-10 mins)...")
param_grid = {'C': [0.1, 1, 10], 'loss': ['hinge', 'squared_hinge']}
grid_svm = GridSearchCV(LinearSVC(max_iter=2000, random_state=42, dual=True),
                         param_grid, cv=3, scoring='f1_weighted', n_jobs=-1)
grid_svm.fit(X_train, y_train)
best_svm = grid_svm.best_estimator_
y_pred_best_svm = best_svm.predict(X_test)
acc_best_svm = accuracy_score(y_test, y_pred_best_svm)
f1_best_svm = f1_score(y_test, y_pred_best_svm, average='weighted')
print(f"  ✅ Tuned SVM — Accuracy: {acc_best_svm:.4f} | F1: {f1_best_svm:.4f}")
print(f"  Best params: {grid_svm.best_params_}")

"""
# ============================================================
# CELL 9 — Cross-Validation (Proves No Overfitting)
# ============================================================
"""

print("Running 5-Fold Cross Validation on Best SVM...")
cv_scores = cross_val_score(best_svm, X_combined, y_spam, cv=5, scoring='f1_weighted', n_jobs=-1)
print(f"\n✅ 5-Fold CV F1 Scores: {cv_scores}")
print(f"   Mean F1: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

# This proves to your supervisor that the model is NOT overfitting
if cv_scores.std() < 0.02:
    print("\n🟢 LOW VARIANCE — Model is stable and NOT overfitting!")
else:
    print("\n🟡 Some variance detected — consider more data or regularization")

"""
# ============================================================
# CELL 10 — Confusion Matrix Plots for Spam Models
# ============================================================

"""

models_spam = {
    'Naive Bayes': (y_pred_mnb, None),
    'Logistic Regression': (y_pred_lr, None),
    'Linear SVM': (y_pred_svm, None),
    'Tuned SVM': (y_pred_best_svm, None),
}

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Confusion Matrices — Spam Email Detection', fontsize=16, fontweight='bold')

for ax, (name, (y_pred, _)) in zip(axes.flatten(), models_spam.items()):
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Ham', 'Spam'], yticklabels=['Ham', 'Spam'])
    ax.set_title(f'{name}', fontsize=12, fontweight='bold')
    ax.set_xlabel('Predicted')
    ax.set_ylabel('Actual')

plt.tight_layout()

# Create the directory if it doesn't exist
import os
save_dir = '/content/drive/MyDrive/spam_detector_models/'
os.makedirs(save_dir, exist_ok=True)

plt.savefig(save_dir + 'confusion_matrices_spam.png', dpi=150)
plt.show()
print("✅ Confusion matrices saved!")

"""# ============================================================
# CELL 11 — ROC Curve (NEW - This impresses evaluators a lot!)
# ============================================================

"""

fig, ax = plt.subplots(figsize=(8, 6))

# LR has predict_proba
lr_proba = lr.predict_proba(X_test)[:, 1]
fpr_lr, tpr_lr, _ = roc_curve(y_test, lr_proba, pos_label=spam_df['label'].unique()[1])
roc_auc_lr = auc(fpr_lr, tpr_lr)
ax.plot(fpr_lr, tpr_lr, label=f'Logistic Regression (AUC = {roc_auc_lr:.3f})', linewidth=2)

# SVM uses decision function
svm_scores = best_svm.decision_function(X_test)
fpr_svm, tpr_svm, _ = roc_curve(y_test, svm_scores, pos_label=spam_df['label'].unique()[1])
roc_auc_svm = auc(fpr_svm, tpr_svm)
ax.plot(fpr_svm, tpr_svm, label=f'Tuned SVM (AUC = {roc_auc_svm:.3f})', linewidth=2)

# MNB
mnb_proba = mnb.predict_proba(X_test)[:, 1]
fpr_mnb, tpr_mnb, _ = roc_curve(y_test, mnb_proba, pos_label=spam_df['label'].unique()[1])
roc_auc_mnb = auc(fpr_mnb, tpr_mnb)
ax.plot(fpr_mnb, tpr_mnb, label=f'Naive Bayes (AUC = {roc_auc_mnb:.3f})', linewidth=2)

# Diagonal reference line
ax.plot([0, 1], [0, 1], 'k--', label='Random Classifier', linewidth=1)

ax.set_xlabel('False Positive Rate', fontsize=12)
ax.set_ylabel('True Positive Rate', fontsize=12)
ax.set_title('ROC Curves — Spam Email Detection', fontsize=14, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/spam_detector_models/roc_curve_spam.png', dpi=150)
plt.show()
print(f"✅ ROC Curves saved!")
print(f"   Best AUC: Tuned SVM = {roc_auc_svm:.4f}")

"""# ============================================================
# CELL 12 — Load Phishing URL Dataset
# ============================================================

"""

phishing_path = '/content/drive/MyDrive/email-phishing-detector/Phising URL detector/PhiUSIIL_Phishing_URL_Dataset.csv'

try:
    phishing_df = pd.read_csv(phishing_path)
    print(f"✅ Phishing dataset loaded. Shape: {phishing_df.shape}")
    print(f"\nLabel distribution:\n{phishing_df['label'].value_counts()}")
    print(f"\nMissing values:\n{phishing_df.isnull().sum().sum()} total")
except FileNotFoundError:
    print(f"❌ File not found: {phishing_path}")
    print("Please check the path to your phishing dataset in Google Drive.")

"""
# ============================================================
# CELL 13 — Feature Engineering for Phishing URLs
# ============================================================
"""

def extract_url_features(url):
    """Extract structural features from URL for ML model"""
    try:
        parsed = urlparse(str(url))
        hostname = parsed.netloc
        path = parsed.path
        query = parsed.query

        features = {
            'url_length': len(str(url)),
            'hostname_length': len(hostname),
            'path_length': len(path),
            'num_dots': str(url).count('.'),
            'num_hyphens': str(url).count('-'),
            'num_slashes': str(url).count('/'),
            'num_at': str(url).count('@'),
            'num_question': str(url).count('?'),
            'num_equals': str(url).count('='),
            'num_ampersand': str(url).count('&'),
            'num_digits': sum(c.isdigit() for c in str(url)),
            'num_subdomains': len(hostname.split('.')) - 2 if hostname else 0,
            'has_https': 1 if str(url).startswith('https') else 0,
            'has_ip': 1 if re.match(r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$', hostname) else 0,
            'has_at_symbol': 1 if '@' in str(url) else 0,
            'is_shortened': 1 if any(s in str(url) for s in ['bit.ly', 'goo.gl', 'tinyurl', 't.co', 'ow.ly']) else 0,
            'num_params': len(query.split('&')) if query else 0,
            'special_char_ratio': sum(not c.isalnum() for c in str(url)) / max(len(str(url)), 1),
            'digit_ratio': sum(c.isdigit() for c in str(url)) / max(len(str(url)), 1),
        }
        return features
    except:
        return {k: 0 for k in ['url_length', 'hostname_length', 'path_length', 'num_dots',
                                 'num_hyphens', 'num_slashes', 'num_at', 'num_question',
                                 'num_equals', 'num_ampersand', 'num_digits', 'num_subdomains',
                                 'has_https', 'has_ip', 'has_at_symbol', 'is_shortened',
                                 'num_params', 'special_char_ratio', 'digit_ratio']}

# Extract features from URL column
print("Extracting URL features...")
url_features = phishing_df['URL'].apply(extract_url_features)
url_features_df = pd.DataFrame(url_features.tolist())

# Drop duplicate columns from original + add new URL features
existing_cols_to_keep = [col for col in phishing_df.columns
                          if col not in url_features_df.columns and col != 'URL' and col != 'Title' and col != 'Domain' and col != 'TLD']

phishing_enhanced = pd.concat([
    phishing_df[existing_cols_to_keep].reset_index(drop=True),
    url_features_df.reset_index(drop=True)
], axis=1)

print(f"✅ Enhanced phishing dataset shape: {phishing_enhanced.shape}")

"""
# ============================================================
# CELL 14 — Prepare Phishing Features + Train-Test Split
# ============================================================
"""

# Remove non-numeric columns and label
drop_cols = ['label']
X_phishing = phishing_enhanced.drop(columns=drop_cols, errors='ignore')

# Keep only numeric columns
X_phishing = X_phishing.select_dtypes(include=[np.number])

# Handle any remaining NaN
X_phishing = X_phishing.fillna(0)

y_phishing = phishing_enhanced['label']

# Log transform skewed features
skewed_cols = X_phishing.columns[X_phishing.skew().abs() > 1].tolist()
for col in skewed_cols:
    X_phishing[col + '_log'] = np.log1p(X_phishing[col].clip(lower=0))

print(f"✅ Phishing feature matrix shape: {X_phishing.shape}")
print(f"   Applied log transform to {len(skewed_cols)} skewed columns")

X_phish_train, X_phish_test, y_phish_train, y_phish_test = train_test_split(
    X_phishing, y_phishing, test_size=0.2, random_state=42, stratify=y_phishing
)

print(f"   Train: {X_phish_train.shape} | Test: {X_phish_test.shape}")

"""
# ============================================================
# CELL 15 — Train ALL Phishing Detection Models
# ============================================================
"""

# --- Model 1: Logistic Regression ---
print("Training Logistic Regression for Phishing...")
lr_phish = LogisticRegression(solver='liblinear', max_iter=1000, random_state=42)
lr_phish.fit(X_phish_train, y_phish_train)
y_pred_lr_phish = lr_phish.predict(X_phish_test)
acc_lr_phish = accuracy_score(y_phish_test, y_pred_lr_phish)
f1_lr_phish = f1_score(y_phish_test, y_pred_lr_phish, average='weighted')
print(f"  ✅ LR  — Accuracy: {acc_lr_phish:.4f} | F1: {f1_lr_phish:.4f}")

# --- Model 2: Linear SVM ---
print("Training Linear SVM for Phishing...")
svm_phish = LinearSVC(max_iter=2000, random_state=42, dual=False)
svm_phish.fit(X_phish_train, y_phish_train)
y_pred_svm_phish = svm_phish.predict(X_phish_test)
acc_svm_phish = accuracy_score(y_phish_test, y_pred_svm_phish)
f1_svm_phish = f1_score(y_phish_test, y_pred_svm_phish, average='weighted')
print(f"  ✅ SVM — Accuracy: {acc_svm_phish:.4f} | F1: {f1_svm_phish:.4f}")

# --- Model 3: Random Forest ---
print("Training Random Forest for Phishing...")
rf_phish = RandomForestClassifier(n_estimators=200, max_depth=20,
                                    random_state=42, n_jobs=-1)
rf_phish.fit(X_phish_train, y_phish_train)
y_pred_rf_phish = rf_phish.predict(X_phish_test)
acc_rf_phish = accuracy_score(y_phish_test, y_pred_rf_phish)
f1_rf_phish = f1_score(y_phish_test, y_pred_rf_phish, average='weighted')
print(f"  ✅ RF  — Accuracy: {acc_rf_phish:.4f} | F1: {f1_rf_phish:.4f}")

print("\n✅ All phishing models trained!")

"""
# ============================================================
# CELL 16 — Cross-Validation for Phishing (Anti-Overfitting Proof)
# ============================================================
"""

print("Running 5-Fold Cross Validation on Random Forest (Phishing)...")
cv_phish = cross_val_score(rf_phish, X_phishing, y_phishing, cv=5, scoring='f1_weighted', n_jobs=-1)
print(f"\n✅ 5-Fold CV F1 Scores: {cv_phish}")
print(f"   Mean F1: {cv_phish.mean():.4f} ± {cv_phish.std():.4f}")

if cv_phish.std() < 0.02:
    print("\n🟢 LOW VARIANCE — Random Forest is stable and generalizes well!")
else:
    print("\n🟡 Some variance detected.")

"""
# ============================================================
# CELL 17 — ROC Curves for Phishing Models
# ============================================================"""

fig, ax = plt.subplots(figsize=(8, 6))

# Logistic Regression (has predict_proba)
lr_phish_proba = lr_phish.predict_proba(X_phish_test)[:, 1]
fpr_lr_p, tpr_lr_p, _ = roc_curve(y_phish_test, lr_phish_proba)
ax.plot(fpr_lr_p, tpr_lr_p, label=f'Logistic Regression (AUC = {auc(fpr_lr_p, tpr_lr_p):.3f})', linewidth=2)

# SVM (decision function)
svm_phish_scores = svm_phish.decision_function(X_phish_test)
fpr_svm_p, tpr_svm_p, _ = roc_curve(y_phish_test, svm_phish_scores)
ax.plot(fpr_svm_p, tpr_svm_p, label=f'Linear SVM (AUC = {auc(fpr_svm_p, tpr_svm_p):.3f})', linewidth=2)

# Random Forest (predict_proba)
rf_phish_proba = rf_phish.predict_proba(X_phish_test)[:, 1]
fpr_rf_p, tpr_rf_p, _ = roc_curve(y_phish_test, rf_phish_proba)
ax.plot(fpr_rf_p, tpr_rf_p, label=f'Random Forest (AUC = {auc(fpr_rf_p, tpr_rf_p):.3f})', linewidth=2)

ax.plot([0, 1], [0, 1], 'k--', label='Random Classifier', linewidth=1)
ax.set_xlabel('False Positive Rate', fontsize=12)
ax.set_ylabel('True Positive Rate', fontsize=12)
ax.set_title('ROC Curves — Phishing URL Detection', fontsize=14, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/spam_detector_models/roc_curve_phishing.png', dpi=150)
plt.show()
print("✅ Phishing ROC Curves saved!")

"""
# ============================================================
# CELL 18 — Feature Importance Plot (Random Forest - Phishing)
# NEW: This shows WHICH features matter most — supervisors love this
# ============================================================"""

feature_names = X_phishing.columns.tolist()
importances = rf_phish.feature_importances_

# Get top 20 features
indices = np.argsort(importances)[::-1][:20]
top_features = [feature_names[i] for i in indices]
top_importances = importances[indices]

fig, ax = plt.subplots(figsize=(10, 7))
bars = ax.barh(range(20), top_importances[::-1], color='steelblue', edgecolor='white')
ax.set_yticks(range(20))
ax.set_yticklabels(top_features[::-1], fontsize=10)
ax.set_xlabel('Feature Importance Score', fontsize=12)
ax.set_title('Top 20 Most Important Features — Phishing Detection\n(Random Forest)', fontsize=13, fontweight='bold')
ax.grid(True, alpha=0.3, axis='x')

# Add value labels on bars
for i, (bar, val) in enumerate(zip(bars, top_importances[::-1])):
    ax.text(val + 0.001, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=8)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/spam_detector_models/feature_importance.png', dpi=150)
plt.show()
print("✅ Feature importance plot saved!")

"""
# ============================================================
# CELL 19 — Master Comparison Table (Both Tasks)
# ============================================================
"""

comparison_data = {
    'Task': ['Spam Detection', 'Spam Detection', 'Spam Detection', 'Spam Detection',
             'Phishing Detection', 'Phishing Detection', 'Phishing Detection'],
    'Model': ['Naive Bayes', 'Logistic Regression', 'Linear SVM', 'Tuned SVM (GridSearch)',
              'Logistic Regression', 'Linear SVM', 'Random Forest'],
    'Accuracy': [acc_mnb, acc_lr, acc_svm, acc_best_svm,
                  acc_lr_phish, acc_svm_phish, acc_rf_phish],
    'Precision': [
        precision_score(y_test, y_pred_mnb, average='weighted'),
        precision_score(y_test, y_pred_lr, average='weighted'),
        precision_score(y_test, y_pred_svm, average='weighted'),
        precision_score(y_test, y_pred_best_svm, average='weighted'),
        precision_score(y_phish_test, y_pred_lr_phish, average='weighted'),
        precision_score(y_phish_test, y_pred_svm_phish, average='weighted'),
        precision_score(y_phish_test, y_pred_rf_phish, average='weighted'),
    ],
    'Recall': [
        recall_score(y_test, y_pred_mnb, average='weighted'),
        recall_score(y_test, y_pred_lr, average='weighted'),
        recall_score(y_test, y_pred_svm, average='weighted'),
        recall_score(y_test, y_pred_best_svm, average='weighted'),
        recall_score(y_phish_test, y_pred_lr_phish, average='weighted'),
        recall_score(y_phish_test, y_pred_svm_phish, average='weighted'),
        recall_score(y_phish_test, y_pred_rf_phish, average='weighted'),
    ],
    'F1-Score': [f1_mnb, f1_lr, f1_svm, f1_best_svm,
                  f1_lr_phish, f1_svm_phish, f1_rf_phish],
}

comparison_df = pd.DataFrame(comparison_data)
comparison_df[['Accuracy', 'Precision', 'Recall', 'F1-Score']] = \
    comparison_df[['Accuracy', 'Precision', 'Recall', 'F1-Score']].round(4)

print("\n" + "="*75)
print("            COMPLETE MODEL PERFORMANCE COMPARISON")
print("="*75)
print(comparison_df.to_string(index=False))
print("="*75)

# Save to CSV
comparison_df.to_csv('/content/drive/MyDrive/spam_detector_models/model_comparison.csv', index=False)
print("\n✅ Comparison table saved to Drive!")

"""

# ============================================================
# CELL 20 — Grouped Bar Chart Comparison (Beautiful!)
# ============================================================
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Model Performance Comparison — FYP: Spam & Phishing Detector',
             fontsize=14, fontweight='bold')

metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
colors = ['#2196F3', '#4CAF50', '#FF9800', '#F44336']

for ax, task in zip(axes, ['Spam Detection', 'Phishing Detection']):
    task_df = comparison_df[comparison_df['Task'] == task].reset_index(drop=True)
    x = np.arange(len(task_df))
    width = 0.2

    for i, (metric, color) in enumerate(zip(metrics, colors)):
        bars = ax.bar(x + i * width, task_df[metric], width, label=metric,
                      color=color, alpha=0.85, edgecolor='white')
        for bar in bars:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                    f'{bar.get_height():.3f}', ha='center', va='bottom',
                    fontsize=6.5, rotation=45)

    ax.set_title(f'{task}', fontsize=12, fontweight='bold')
    ax.set_xticks(x + width * 1.5)
    ax.set_xticklabels(task_df['Model'], rotation=20, ha='right', fontsize=9)
    ax.set_ylim(0.85, 1.03)
    ax.set_ylabel('Score')
    ax.legend(loc='lower right', fontsize=9)
    ax.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/spam_detector_models/model_comparison_chart.png', dpi=150)
plt.show()
print("✅ Comparison chart saved!")

"""
# ============================================================
# CELL 21 — Add DistilBERT / Pre-trained Transformer Comparison
# NEW: This is what separates your project from others!
# ============================================================
"""

"""
NOTE: Run this cell ONLY if you have GPU enabled in Colab
      Runtime > Change runtime type > T4 GPU
"""

from transformers import pipeline

print("Loading pre-trained spam detection transformer model...")
print("(This will download ~50MB model — first time only)")

# This is a BERT-based model pre-trained on Enron spam dataset
spam_transformer = pipeline(
    "text-classification",
    model="mrm8488/bert-tiny-finetuned-enron-spam-detection",
    device=0  # Use GPU. Change to -1 if no GPU
)

# Test on a sample of your test data
print("\nEvaluating transformer on 500 test samples...")
sample_texts = spam_df['text_processed'].iloc[:500].tolist()
sample_labels = spam_df['label'].iloc[:500].tolist()

# Get predictions
transformer_preds_raw = spam_transformer(sample_texts, batch_size=32, truncation=True, max_length=512)

# Map labels — model returns 'LABEL_1' for spam, 'LABEL_0' for ham
label_map = {'LABEL_1': 1, 'LABEL_0': 0, 'spam': 1, 'ham': 0}
transformer_preds = []
for p in transformer_preds_raw:
    label = p['label'].upper()
    transformer_preds.append(label_map.get(label, 0))

# Also get SVM predictions on same 500 samples for fair comparison
X_sample = tfidf_vectorizer.transform(sample_texts)
sample_num = spam_df[['text_length_transformed']].iloc[:500].values

if 'urls_transformed' in spam_df.columns:
    sample_num = spam_df[['urls_transformed', 'text_length_transformed']].iloc[:500].values

X_sample_combined = hstack([X_sample, csr_matrix(sample_num)])
svm_sample_preds = best_svm.predict(X_sample_combined)

# Evaluate both
bert_f1 = f1_score(sample_labels, transformer_preds, average='weighted')
svm_sample_f1 = f1_score(sample_labels, svm_sample_preds, average='weighted')
bert_acc = accuracy_score(sample_labels, transformer_preds)
svm_sample_acc = accuracy_score(sample_labels, svm_sample_preds)

print(f"\n{'='*50}")
print(f"  CLASSICAL ML vs TRANSFORMER COMPARISON")
print(f"{'='*50}")
print(f"  Tuned SVM    — Accuracy: {svm_sample_acc:.4f} | F1: {svm_sample_f1:.4f}")
print(f"  DistilBERT   — Accuracy: {bert_acc:.4f} | F1: {bert_f1:.4f}")
print(f"{'='*50}")
print("\n✅ Transformer comparison complete!")
print("   This comparison demonstrates awareness of SOTA methods.")

"""
# ============================================================
# CELL 22 — Save All Models to Google Drive
# ============================================================
"""

save_dir = '/content/drive/MyDrive/spam_detector_models/'
os.makedirs(save_dir, exist_ok=True)

# Save spam models
with open(save_dir + 'tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf_vectorizer, f)

with open(save_dir + 'spam_best_svm.pkl', 'wb') as f:
    pickle.dump(best_svm, f)

with open(save_dir + 'spam_lr.pkl', 'wb') as f:
    pickle.dump(lr, f)

# Save phishing models
with open(save_dir + 'phishing_rf.pkl', 'wb') as f:
    pickle.dump(rf_phish, f)

with open(save_dir + 'phishing_lr.pkl', 'wb') as f:
    pickle.dump(lr_phish, f)

# Save feature column names for phishing (needed for prediction)
with open(save_dir + 'phishing_feature_cols.pkl', 'wb') as f:
    pickle.dump(X_phishing.columns.tolist(), f)

print("✅ All models saved successfully!")

# Provide more comprehensive feedback on saved files
print(f"\nContents of '{save_dir}':")
if os.path.exists(save_dir) and os.listdir(save_dir):
    for fname in os.listdir(save_dir):
        file_path = os.path.join(save_dir, fname)
        if os.path.isfile(file_path):
            size = os.path.getsize(file_path) / 1024 # size in KB
            print(f"   📁 {fname}  ({size:.1f} KB)")
else:
    print("   No files found in the directory after saving. Please check Google Drive permissions.")

"""
# ============================================================
# CELL FP-1 — Precision-Focused Model Training
# This minimizes false positives (ham marked as spam)
# ============================================================
"""

from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from sklearn.calibration import CalibratedClassifierCV
import numpy as np

# Initialize OPTIMAL_THRESHOLD with a default value to ensure it's always defined.
# This will be updated by the threshold analysis if good_thresholds are found.
OPTIMAL_THRESHOLD = 0.6

# Step 1: Calibrate SVM to get proper probability scores
# (LinearSVC doesn't give probabilities by default)
print("Calibrating SVM for probability scores...")
calibrated_svm = CalibratedClassifierCV(
    LinearSVC(C=1.0, max_iter=2000, random_state=42, dual=False),
    cv=3,
    method='sigmoid'
)
calibrated_svm.fit(X_train, y_train)
print("✅ Calibrated SVM ready!")

# Step 2: Find optimal threshold to minimize false positives
print("\nFinding optimal threshold to minimize false positives...")

# Get probability scores on test set
y_proba = calibrated_svm.predict_proba(X_test)

# Figure out which column is "spam"
classes = calibrated_svm.classes_
spam_class_index = list(classes).index(1) if 1 in classes else list(classes).index('spam')
spam_proba = y_proba[:, spam_class_index]

# Test different thresholds
thresholds = np.arange(0.3, 0.95, 0.05)
results = []

for thresh in thresholds:
    y_pred_thresh = (spam_proba >= thresh).astype(int)
    # Convert y_test to binary 0/1 for comparison
    y_test_binary = (y_test == classes[spam_class_index]).astype(int)

    fp = np.sum((y_pred_thresh == 1) & (y_test_binary == 0))  # Ham marked as spam
    fn = np.sum((y_pred_thresh == 0) & (y_test_binary == 1))  # Spam missed
    tp = np.sum((y_pred_thresh == 1) & (y_test_binary == 1))
    tn = np.sum((y_pred_thresh == 0) & (y_test_binary == 0))

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0  # False Positive Rate

    results.append({
        'threshold': round(thresh, 2),
        'false_positives': fp,
        'false_positive_rate': round(fpr * 100, 2),
        'precision': round(precision, 4),
        'recall': round(recall, 4),
        'f1': round(f1, 4)
    })

results_df = pd.DataFrame(results)
print("\n" + "="*70)
print("  THRESHOLD ANALYSIS — False Positive vs Spam Detection Trade-off")
print("="*70)
print(results_df.to_string(index=False))
print("="*70)

# Find best threshold: minimize false positives while keeping recall > 0.85
good_thresholds = results_df[results_df['recall'] >= 0.85]
if len(good_thresholds) > 0:
    best_row = good_thresholds.loc[good_thresholds['false_positives'].idxmin()]
    OPTIMAL_THRESHOLD = best_row['threshold'] # Update global OPTIMAL_THRESHOLD
    print(f"\n✅ Recommended Threshold: {OPTIMAL_THRESHOLD}")
    print(f"   False Positives: {best_row['false_positives']}")
    print(f"   False Positive Rate: {best_row['false_positive_rate']}% বিদেশে)")
    print(f"   Precision: {best_row['precision']} | Recall: {best_row['recall']}")
else:
    # OPTIMAL_THRESHOLD is already initialized to 0.6, so this isn't strictly needed here
    # but kept for clarity if logic changes.
    print(f"\n⚠️ Using default threshold: {OPTIMAL_THRESHOLD} as no optimal found with criteria.")

"""

# ============================================================
# CELL FP-2 — Threshold Visualization
# ============================================================
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Threshold Tuning — Reducing False Positives', fontsize=14, fontweight='bold')

# Plot 1: False Positives vs Threshold
ax1 = axes[0]
ax1.plot(results_df['threshold'], results_df['false_positives'],
         color='red', linewidth=2, marker='o', markersize=5)
ax1.axvline(x=OPTIMAL_THRESHOLD, color='green', linestyle='--',
            linewidth=2, label=f'Optimal ({OPTIMAL_THRESHOLD})')
ax1.set_xlabel('Threshold', fontsize=11)
ax1.set_ylabel('False Positives (Ham → Spam)', fontsize=11)
ax1.set_title('False Positives at Different Thresholds', fontsize=11)
ax1.legend()
ax1.grid(True, alpha=0.3)

# Plot 2: Precision vs Recall tradeoff
ax2 = axes[1]
ax2.plot(results_df['threshold'], results_df['precision'],
         color='blue', linewidth=2, marker='o', markersize=5, label='Precision')
ax2.plot(results_df['threshold'], results_df['recall'],
         color='orange', linewidth=2, marker='s', markersize=5, label='Recall')
ax2.plot(results_df['threshold'], results_df['f1'],
         color='green', linewidth=2, marker='^', markersize=5, label='F1-Score')
ax2.axvline(x=OPTIMAL_THRESHOLD, color='red', linestyle='--',
            linewidth=2, label=f'Optimal ({OPTIMAL_THRESHOLD})')
ax2.set_xlabel('Threshold', fontsize=11)
ax2.set_ylabel('Score', fontsize=11)
ax2.set_title('Precision / Recall / F1 vs Threshold', fontsize=11)
ax2.legend()
ax2.grid(True, alpha=0.3)
ax2.set_ylim(0.7, 1.02)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/spam_detector_models/threshold_analysis.png', dpi=150)
plt.show()
print("✅ Threshold analysis chart saved!")

"""

# ============================================================
# CELL FP-3 — Smart Whitelist for Common Legitimate Emails
# ============================================================
"""

# These keywords in subject/body = almost certainly NOT spam
WHITELIST_KEYWORDS = [
    # Transactional emails
    'your order', 'order confirmation', 'invoice', 'receipt',
    'your booking', 'reservation confirmed', 'your ticket',
    'payment received', 'payment confirmation',
    # Account emails
    'password reset', 'verify your email', 'account created',
    'welcome to', 'login attempt', 'security alert',
    # Work/professional
    'meeting', 'agenda', 'project update', 'deadline',
    'pull request', 'github', 'jenkins', 'jira',
    # Notifications
    'your subscription', 'newsletter', 'unsubscribe',
    'tracking number', 'shipped', 'delivered',
]

def check_whitelist(text):
    """Returns True if email matches whitelist (likely legitimate)"""
    text_lower = text.lower()
    for keyword in WHITELIST_KEYWORDS:
        if keyword in text_lower:
            return True
    return False

print("✅ Whitelist created with", len(WHITELIST_KEYWORDS), "safe keyword patterns")
print("\nExample whitelist matches:")
test_texts = [
    "Your order confirmation #12345",
    "Meeting agenda for tomorrow",
    "WIN FREE IPHONE CLICK NOW",
    "Password reset request"
]
for t in test_texts:
    result = check_whitelist(t)
    icon = "✅ Safe (whitelisted)" if result else "🔍 Needs ML check"
    print(f"   '{t}' → {icon}")

"""
# ============================================================
# CELL FP-4 — Smart Predict Function (False Positive Resistant)
# ============================================================
"""

def predict_spam_smart(subject, body, threshold=None):
    """
    Smart spam detection with false positive protection.
    Uses: Whitelist check → ML model → Threshold → Final verdict
    Returns: (display_message, spam_probability, alert_message)
    """
    if threshold is None:
        threshold = OPTIMAL_THRESHOLD

    alert_message = ""

    if not subject.strip() and not body.strip():
        return " ☢️ Please enter subject or body text.", 0.0, alert_message

    text = (subject + " " + body).strip()

    # Step 1: Whitelist check
    if check_whitelist(text):
        return ("✅ LEGITIMATE — Whitelisted Pattern\nThis email matches known legitimate patterns (order/receipt/meeting etc.)\nConfidence: 99%", 0.01, alert_message)

    # Step 2: ML prediction with calibrated probabilities
    processed = preprocess_text(text)
    features_tfidf = tfidf_vectorizer.transform([processed])

    # Add numerical features
    text_len = np.log1p(len(processed))
    url_count = np.log1p(text.count('http'))
    dummy_num = np.array([[url_count, text_len]])
    features_combined = hstack([features_tfidf, csr_matrix(dummy_num)])

    proba = calibrated_svm.predict_proba(features_combined)[0]
    spam_prob = proba[spam_class_index]
    ham_prob = 1 - spam_prob

    # Step 3: Apply threshold
    if spam_prob >= threshold:
        risk_level = "⚠️ HIGH RISK" if spam_prob > 0.85 else "⚠️ MEDIUM RISK"
        alert_message = "⚠️ Possible Phishing Email Detected! Proceed with caution."
        return (f"{risk_level} — SPAM DETECTED\n"
                f"Spam Probability: {spam_prob*100:.1f}%\n"
                f"Threshold Used: {threshold}\n\n"
                f"This email shows strong spam patterns."), spam_prob, alert_message
    else:
        confidence = ham_prob * 100
        return (f"✅ LEGITIMATE EMAIL\n"
                f"Ham Probability: {ham_prob*100:.1f}%\n"
                f"Spam Probability: {spam_prob*100:.1f}% (below threshold of {threshold})\n\n"
                f"This email appears genuine."), spam_prob, alert_message


# Test it
print("\nTesting smart predict function:")
result, prob, alert = predict_spam_smart("Your order confirmation", "Your Amazon order #123 has been confirmed")
print(f"Test 1: {result}\n")

result, prob, alert = predict_spam_smart("WIN FREE IPHONE", "Click now to claim your free prize worth $1000!!!")
print(f"Test 2: {result}\n Alert: {alert}\n")

result, prob, alert = predict_spam_smart("Meeting Tomorrow", "Hi team, please join the standup at 10am")
print(f"Test 3: {result}")

"""
# ============================================================
# CELL FP-5 — CSV Bulk Upload + Gmail API Functions
# ============================================================
"""

import base64
import json
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# --- Function 1: Process uploaded CSV file ---
def process_csv_emails(csv_file):
    """
    Process a CSV file containing emails.
    Expected columns: subject, body (or just body/text)
    Returns a DataFrame with predictions.
    """
    try:
        df = pd.read_csv(csv_file.name)
        print(f"Loaded CSV: {df.shape[0]} emails, columns: {df.columns.tolist()}")

        # Auto-detect columns
        subject_col = None
        body_col = None

        for col in df.columns:
            col_lower = col.lower()
            if 'subject' in col_lower:
                subject_col = col
            elif 'body' in col_lower or 'text' in col_lower or 'message' in col_lower or 'content' in col_lower:
                body_col = col

        if body_col is None:
            # Use first text column
            text_cols = df.select_dtypes(include='object').columns
            if len(text_cols) > 0:
                body_col = text_cols[0]
            else:
                return None, "❌ No text columns found in CSV"

        results = []
        for _, row in df.iterrows():
            subject = str(row[subject_col]) if subject_col else ''
            body = str(row[body_col]) if body_col else ''
            verdict, prob = predict_spam_smart(subject, body, threshold=OPTIMAL_THRESHOLD)
            label = "🚨 SPAM" if prob >= OPTIMAL_THRESHOLD else "✅ HAM"
            results.append({
                'Subject': subject[:60] + '...' if len(subject) > 60 else subject,
                'Body Preview': body[:80] + '...' if len(body) > 80 else body,
                'Prediction': label,
                'Spam Probability': f"{prob*100:.1f}%",
            })

        results_df = pd.DataFrame(results)
        spam_count = sum(1 for r in results if '🚨' in r['Prediction'])
        ham_count = len(results) - spam_count
        summary = f"📊 Analysis Complete!\n✅ Legitimate: {ham_count} | 🚨 Spam: {spam_count} | Total: {len(results)}"
        return results_df, summary

    except Exception as e:
        return None, f"❌ Error processing CSV: {str(e)}"


# --- Function 2: Gmail API Integration ---
GMAIL_SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

def authenticate_gmail():
    """
    Authenticate with Gmail API.
    User needs to upload credentials.json from Google Cloud Console.
    """
    try:
        creds = None
        token_path = '/content/drive/MyDrive/spam_detector_models/gmail_token.json'
        creds_path = '/content/drive/MyDrive/spam_detector_models/credentials.json'

        if os.path.exists(token_path):
            creds = Credentials.from_authorized_user_file(token_path, GMAIL_SCOPES)

        if not creds or not creds.valid:
            if not os.path.exists(creds_path):
                return None, "❌ credentials.json not found. Please upload it to your Drive folder."
            flow = InstalledAppFlow.from_client_secrets_file(creds_path, GMAIL_SCOPES)
            creds = flow.run_local_server(port=0)
            with open(token_path, 'w') as token:
                token.write(creds.to_json())

        service = build('gmail', 'v1', credentials=creds)
        return service, "✅ Gmail connected!"
    except Exception as e:
        return None, f"❌ Gmail auth failed: {str(e)}"


def fetch_and_analyze_gmail(num_emails=20):
    """
    Fetch recent emails from Gmail inbox and analyze them.
    Returns DataFrame with spam predictions.
    """
    service, msg = authenticate_gmail()
    if service is None:
        return None, msg

    try:
        results = service.users().messages().list(
            userId='me', labelIds=['INBOX'], maxResults=num_emails
        ).execute()
        messages = results.get('messages', [])

        if not messages:
            return None, "📭 No emails found in inbox."

        email_results = []
        for msg_ref in messages:
            try:
                msg = service.users().messages().get(
                    userId='me', id=msg_ref['id'], format='full'
                ).execute()

                headers = msg['payload'].get('headers', [])
                subject = next((h['value'] for h in headers if h['name'] == 'Subject'), 'No Subject')
                sender = next((h['value'] for h in headers if h['name'] == 'From'), 'Unknown')

                # Extract body
                body = ''
                payload = msg['payload']
                if 'parts' in payload:
                    for part in payload['parts']:
                        if part['mimeType'] == 'text/plain':
                            data = part['body'].get('data', '')
                            if data:
                                body = base64.urlsafe_b64decode(data).decode('utf-8', errors='ignore')
                                break
                elif 'body' in payload:
                    data = payload['body'].get('data', '')
                    if data:
                        body = base64.urlsafe_b64decode(data).decode('utf-8', errors='ignore')

                verdict, prob = predict_spam_smart(subject, body[:500], threshold=OPTIMAL_THRESHOLD)
                label = "🚨 SPAM" if prob >= OPTIMAL_THRESHOLD else "✅ HAM"

                email_results.append({
                    'From': sender[:40],
                    'Subject': subject[:60],
                    'Prediction': label,
                    'Spam Probability': f"{prob*100:.1f}%",
                })

            except Exception as e:
                continue

        results_df = pd.DataFrame(email_results)
        spam_count = sum(1 for r in email_results if '🚨' in r['Prediction'])
        ham_count = len(email_results) - spam_count
        summary = f"📊 Gmail Analysis Done!\n✅ Legitimate: {ham_count} | 🚨 Spam: {spam_count} | Total: {len(email_results)}"
        return results_df, summary

    except Exception as e:
        return None, f"❌ Error fetching Gmail: {str(e)}"


print("✅ CSV + Gmail functions ready!")

# Gmail credentials save karo session ke liye
GMAIL_ADDRESS = "YOUR_EMAIL_HERE"
GMAIL_APP_PASSWORD = "YOUR_PASSWORD_HERE"

def analyze_gmail_imap(num_emails):
    try:
        results_df = fetch_gmail_imap(GMAIL_ADDRESS, GMAIL_APP_PASSWORD, int(num_emails))
        spam_count = sum(1 for p in results_df['Prediction'] if '🚨' in p)
        ham_count = len(results_df) - spam_count
        summary = f"📊 Gmail Analysis Complete!\n✅ Legitimate: {ham_count} | 🚨 Spam: {spam_count} | Total: {len(results_df)}"
        return results_df, summary
    except Exception as e:
        return None, f"❌ Error: {str(e)}"

print("✅ Gmail analyzer ready!")

"""

# ============================================================
# CELL FP-6 — COMPLETE UPGRADED GRADIO APP
# With: Threshold slider + CSV upload + Gmail integration
# ============================================================
"""

import gradio as gr

with gr.Blocks(title="🛡️ Smart Spam & Phishing Detector", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🛡️ Smart Spam Email & Phishing URL Detector
    ### FYP Project — AI-Powered with False Positive Protection
    ---
    """)

    with gr.Tabs():

        # TAB 1: Single Email
        with gr.Tab("📧 Check Single Email"):
            with gr.Row():
                with gr.Column():
                    email_subject = gr.Textbox(label="📌 Email Subject", lines=1)
                    email_body = gr.Textbox(label="📝 Email Body", lines=6)
                    threshold_slider = gr.Slider(
                        minimum=0.3, maximum=0.95, value=OPTIMAL_THRESHOLD, step=0.05,
                        label=f"🎚️ Spam Threshold (Recommended: {OPTIMAL_THRESHOLD})"
                    )
                    spam_btn = gr.Button("🔍 Analyze Email", variant="primary")
                with gr.Column():
                    spam_output = gr.Textbox(label="🔎 Result", lines=8)

            gr.Examples(
                examples=[
                    ["WIN FREE iPhone NOW!", "Click here IMMEDIATELY to claim your $1000 prize!"],
                    ["Meeting tomorrow", "Hi team please join standup at 10am."],
                    ["Your account suspended", "Verify bank details immediately or account deleted."],
                    ["Order confirmation", "Your Amazon order will arrive in 3-5 days."],
                ],
                inputs=[email_subject, email_body]
            )
            spam_btn.click(
                fn=lambda s, b, t: predict_spam_smart(s, b, t)[0],
                inputs=[email_subject, email_body, threshold_slider],
                outputs=spam_output
            )

        # TAB 2: CSV Upload
        with gr.Tab("📂 Bulk CSV Analysis"):
            with gr.Row():
                with gr.Column():
                    csv_upload = gr.File(label="📁 Upload CSV", file_types=[".csv"])
                    csv_btn = gr.Button("🔍 Analyze All Emails", variant="primary")
                    csv_summary = gr.Textbox(label="📊 Summary", lines=3)
            csv_results = gr.Dataframe(label="📋 Results", wrap=True)
            csv_btn.click(fn=process_csv_emails, inputs=csv_upload, outputs=[csv_results, csv_summary])

        # TAB 3: Gmail IMAP (REAL INTEGRATION!)
        with gr.Tab("📬 Gmail Live Integration"):
            gr.Markdown("""
            ### 🔴 Live Gmail Inbox Scanner
            **Directly connected to real Gmail inbox via IMAP**
            """)
            with gr.Row():
                with gr.Column():
                    num_slider = gr.Slider(minimum=5, maximum=500, value=500, step=5,
                                          label="📩 Number of emails to fetch")
                    gmail_btn = gr.Button("📬 Scan Gmail Inbox NOW", variant="primary", size="lg")
                    gmail_summary = gr.Textbox(label="📊 Summary", lines=3)
            gmail_results = gr.Dataframe(label="📋 Your Inbox Analysis", wrap=True)
            gmail_btn.click(fn=analyze_gmail_imap, inputs=num_slider,
                           outputs=[gmail_results, gmail_summary])

            gr.Markdown("""
            > 🔒 **Privacy:** Emails processed locally in Colab. Nothing stored anywhere.
            """)

        # TAB 4: Phishing URL
        with gr.Tab("🔗 Phishing URL Detector"):
            with gr.Row():
                with gr.Column():
                    url_input = gr.Textbox(label="🌐 Enter URL", lines=1)
                    url_btn = gr.Button("🔍 Analyze URL", variant="primary")
                with gr.Column():
                    url_output = gr.Textbox(label="🔎 Security Analysis", lines=10)
            gr.Examples(
                examples=[
                    ["https://www.google.com"],
                    ["http://192.168.1.1/login/bank-verify.php"],
                    ["http://paypal-secure-login.verify-account.com/confirm"],
                    ["https://github.com/user/repo"],
                ],
                inputs=url_input
            )
            url_btn.click(fn=predict_phishing_url, inputs=url_input, outputs=url_output)

        # TAB 5: Dashboard
        with gr.Tab("📊 Model Performance"):
            gr.Dataframe(value=comparison_df, label="All Models Comparison", wrap=True)
            gr.Markdown(f"""
            ### ✅ Key Features:
            - **False Positive Protection** — Threshold: `{OPTIMAL_THRESHOLD}`
            - **Gmail IMAP Integration** — Real inbox scanning
            - **Bulk CSV Analysis** — Multiple emails at once
            - **ML-based Phishing Detection** — Random Forest
            """)

demo.launch(share=True, debug=False)